# Generated by Django 4.1.7 on 2023-03-14 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='weight')),
                ('length', models.FloatField(verbose_name='length')),
                ('height', models.FloatField(verbose_name='height')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=50, verbose_name='gender')),
                ('lifeStatus', models.CharField(default='ALIVE', max_length=50, verbose_name='lifeStatus')),
                ('chippingDateTime', models.DateTimeField(auto_now_add=True)),
                ('deathDateTime', models.DateTimeField(editable=False, null=True)),
                ('animalTypes', models.ManyToManyField(blank=True, related_name='animalTypes', to='animals.animaltypes')),
                ('chipperId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('chippingLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.locations')),
                ('visitedLocations', models.ManyToManyField(blank=True, related_name='visitedLocations', to='animals.locations')),
            ],
        ),
    ]
